<a href="https://colab.research.google.com/github/s26673/POSI_MON1/blob/main/EWD_11_%C4%87wiczenia_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Wstęp do python pandas

1. Zaimportuj (oraz, jeżeli istnieje taka potrzeba - zainstaluj) biblioteki numpy oraz pandas.

In [27]:
import numpy as np
import pandas as pd

2. Utwórz nowy pandas DataFrame, niech składa się z kolumny składającej się z ciągu liczb od 0 do 12 nazywającej się index, oraz kolumny składającej się z ciągu liczb [-10, -8, -6, -4, -2, 0, 2, 4, 6, 8, 10, 12, 14] nazywającej się numbers, z czego do uzyskania obu ciągów wykorzystaj funkcję range. Niech kolumna index będzie traktowana jako indeks tego DataFrame

In [28]:
index_values = list(range(13))
numbers_values = list(range(-10, 16, 2))

df = pd.DataFrame({
    "index": index_values,
    "numbers": numbers_values
})

df = df.set_index("index")

df

       numbers
index
0          -10
1           -8
2           -6
3           -4
4           -2
5            0
6            2
7            4
8            6
9            8
10          10
11          12
12          14

3. Dodaj do tego DataFrame kolumnę zawierającą liczby z kolumny numbers podzielone przez 2 i nazwij ją divided2

In [30]:
df["divided2"] = df["numbers"] / 2

df

       numbers  divided2
index
0          -10      -5.0
1           -8      -4.0
2           -6      -3.0
3           -4      -2.0
4           -2      -1.0
5            0       0.0
6            2       1.0
7            4       2.0
8            6       3.0
9            8       4.0
10          10       5.0
11          12       6.0
12          14       7.0

4. Pomnóż przez siebie wartości z kolumn numbers i divided2, zapisz je w kolumnie multiplied

In [31]:
df["multiplied"] = df["numbers"] * df["divided2"]

df

       numbers  divided2  multiplied
index
0          -10      -5.0        50.0
1           -8      -4.0        32.0
2           -6      -3.0        18.0
3           -4      -2.0         8.0
4           -2      -1.0         2.0
5            0       0.0         0.0
6            2       1.0         2.0
7            4       2.0         8.0
8            6       3.0        18.0
9            8       4.0        32.0
10          10       5.0        50.0
11          12       6.0        72.0
12          14       7.0        98.0

5. Dodaj do DataFrame nową kolumnę nazwaną "Powers of 2", która będzie składała się z wartości uzyskanych z podniesienia do potęgi liczby 2, z czego stopień potęgi będzie określany przez wartości znajdujące się w kolumnie divided2. Zaokrągl te wartości do 2 miejsc po przecinku

In [32]:
df["Powers of 2"] = round(2 ** df["divided2"], 2)

df

       numbers  divided2  multiplied  Powers of 2
index
0          -10      -5.0        50.0         0.03
1           -8      -4.0        32.0         0.06
2           -6      -3.0        18.0         0.12
3           -4      -2.0         8.0         0.25
4           -2      -1.0         2.0         0.50
5            0       0.0         0.0         1.00
6            2       1.0         2.0         2.00
7            4       2.0         8.0         4.00
8            6       3.0        18.0         8.00
9            8       4.0        32.0        16.00
10          10       5.0        50.0        32.00
11          12       6.0        72.0        64.00
12          14       7.0        98.0       128.00

6. Napisz funkcję sprawdzającą, czy dana liczba jest pierwsza, zracającą True bądź False. Dla liczb nienależących do żadnej z tych kategorii zwróć None. Dodaj do DataFrame kolumnę prime, która będzie zawierała tę flagę obliczoną na podstawie wartości indeksu.

In [33]:
def is_prime(n):

    if n < 2:
        return False

    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False

    return True

In [34]:
def is_prime(n):

    if n < 2:
        return None

    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False

    return True

7. Odfiltruj z DataFrame te rekordy, które zawierają None w kolumnie prime.

In [35]:
df["prime"] = df.index.map(is_prime)

df

       numbers  divided2  multiplied  Powers of 2  prime
index
0          -10      -5.0        50.0         0.03   None
1           -8      -4.0        32.0         0.06   None
2           -6      -3.0        18.0         0.12   True
3           -4      -2.0         8.0         0.25   True
4           -2      -1.0         2.0         0.50  False
5            0       0.0         0.0         1.00   True
6            2       1.0         2.0         2.00  False
7            4       2.0         8.0         4.00   True
8            6       3.0        18.0         8.00  False
9            8       4.0        32.0        16.00  False
10          10       5.0        50.0        32.00  False
11          12       6.0        72.0        64.00   True
12          14       7.0        98.0       128.00  False

8. Dodaj kolejną kolumnę special, która zawierać będzie wartości znajdujące się w kolumnie numbers pomnożone przez 2 jeżeli indeks tego wiersza należy do liczb pierwszych, oraz liczbę 1 w przeciwnym wypadku. Nazwij ją "Do if Prime".

In [36]:
df = df[df["prime"].notna()]

df

       numbers  divided2  multiplied  Powers of 2  prime
index
2           -6      -3.0        18.0         0.12   True
3           -4      -2.0         8.0         0.25   True
4           -2      -1.0         2.0         0.50  False
5            0       0.0         0.0         1.00   True
6            2       1.0         2.0         2.00  False
7            4       2.0         8.0         4.00   True
8            6       3.0        18.0         8.00  False
9            8       4.0        32.0        16.00  False
10          10       5.0        50.0        32.00  False
11          12       6.0        72.0        64.00   True
12          14       7.0        98.0       128.00  False

In [37]:
df["Do if Prime"] = np.where(df["prime"], df["numbers"] * 2, 1)

df

/tmp/ipykernel_435/353426298.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Do if Prime"] = np.where(df["prime"], df["numbers"] * 2, 1)

       numbers  divided2  multiplied  Powers of 2  prime  Do if Prime
index
2           -6      -3.0        18.0         0.12   True          -12
3           -4      -2.0         8.0         0.25   True           -8
4           -2      -1.0         2.0         0.50  False            1
5            0       0.0         0.0         1.00   True            0
6            2       1.0         2.0         2.00  False            1
7            4       2.0         8.0         4.00   True            8
8            6       3.0        18.0         8.00  False            1
9            8       4.0        32.0        16.00  False            1
10          10       5.0        50.0        32.00  False            1
11          12       6.0        72.0        64.00   True           24
12          14       7.0        98.0       128.00  False            1

9. Usuń z DataFrame kolumnę prime na 3 sposoby, nie wymieniając nazw kolumn, które chesz zatrzymać.

In [38]:
df = df.drop(columns=["prime"])

In [39]:
df = df.drop("prime", axis=1, errors='ignore')

In [40]:
df = df.loc[:, df.columns != "prime"]

10. Dodaj kolejną kolumnę Sum zawierającą sumę z wartości wszystkich kolumn niebędących indeksem.

In [41]:
df["Sum"] = df.sum(axis=1)

df

       numbers  divided2  multiplied  Powers of 2  Do if Prime     Sum
index
2           -6      -3.0        18.0         0.12          -12   -2.88
3           -4      -2.0         8.0         0.25           -8   -5.75
4           -2      -1.0         2.0         0.50            1    0.50
5            0       0.0         0.0         1.00            0    1.00
6            2       1.0         2.0         2.00            1    8.00
7            4       2.0         8.0         4.00            8   26.00
8            6       3.0        18.0         8.00            1   36.00
9            8       4.0        32.0        16.00            1   61.00
10          10       5.0        50.0        32.00            1   98.00
11          12       6.0        72.0        64.00           24  178.00
12          14       7.0        98.0       128.00            1  248.00

11. Wygeneruj ciąg 11 cyfr pierwszych, a następnie dodaj je do DataFrame w kolumnie "Prime Numbers"

In [42]:
def generate_primes(n):

    primes = []
    num = 2

    while len(primes) < n:
        if is_prime(num):
            primes.append(num)
        num += 1

    return primes

12. Dodaj kolejną kolumnę "Sum Previous", która będzie sumowała aktualną i poprzednią wartość z kolumny "Prime Numbers". Dodaj kolumnę "Sum Previous Cumulative" liczącą kumulatywną sumę na podstawie wartości z kolumny "Prime Numbers".

In [43]:
df["Prime Numbers"] = generate_primes(len(df))

df

,numbers,divided2,multiplied,Powers of 2,Do if Prime,Sum,Prime Numbers
index,,,,,,,
2,-6,-3.0,18.0,0.12,-12,-2.88,2
3,-4,-2.0,8.0,0.25,-8,-5.75,3
4,-2,-1.0,2.0,0.50,1,0.50,5
5,0,0.0,0.0,1.00,0,1.00,7
6,2,1.0,2.0,2.00,1,8.00,11
7,4,2.0,8.0,4.00,8,26.00,13
8,6,3.0,18.0,8.00,1,36.00,17
9,8,4.0,32.0,16.00,1,61.00,19
10,10,5.0,50.0,32.00,1,98.00,23
11,12,6.0,72.0,64.00,24,178.00,29
12,14,7.0,98.0,128.00,1,248.00,31

13. Oblicz następujące agregacje wartości z kolumny multiplied po grupowaniu wierszy na podstawie parzystości wartości w kolumnie divided2: suma, średnia i liczba (wykorzystaj metodę groupby()).

In [44]:
df["even"] = df["divided2"] % 2 == 0

In [45]:
result = df.groupby("even")["multiplied"].agg(["sum", "mean", "count"])

result

         sum       mean  count
even
False  188.0  31.333333      6
True   120.0  24.000000      5